project:
  type: book
  output-dir: docs


book:
  title: "Numbers, Sequences and Series"
  subtitle: "Lecture Notes"
  author: 
    - name: "Dr. Silvio Fanzon"
      affiliations: "University of Hull, UK"
      email: "S.Fanzon@hull.ac.uk"
      url: "https://www.silviofanzon.com"
  date: "20 09 2023" 
  # To enter today's date replace by today
  # Enter date formatted as dd MM yyyy
  date-format: "D MMM YYYY"
  downloads: pdf
  favicon: images/favicon.png
  search:
    location: navbar
    type: overlay
  page-footer:
    center: 
      - text: "License"
        href: sections/license.qmd
      - text: "Contact" 
        href: https://www.silviofanzon.com/contact
  navbar:
    search: true
    pinned: false
    background: black
    foreground: "#E8E8E8"
  sidebar:
    search: false


    
  chapters:
    - index.qmd

    - sections/chap_1_0.qmd
    - sections/chap_1_1.qmd
    - sections/chap_1_2.qmd

    
    - sections/chap_2_0.qmd


    - sections/chap_3_0.qmd

    - sections/license.qmd
    
    - sections/references.qmd




bibliography: teaching.bib
csl: elsevier-with-titles.csl



format:

  html:
    toc: true
    toc-title: On this page
    toc-location: right
    code-overflow: wrap
    execute:
      freeze: auto
    theme:
      light: [flatly, theme-custom.scss]
      dark: [darkly]
    fig-align: center
    fig-cap-location: bottom
    link-external-icon: true

  
  pdf:
    documentclass: scrreprt
    fontsize: 13pt
    geometry:
      - top=25mm
      - left=15mm
      - right=15mm
      - bottom=15mm
      - heightrounded
    link-citations: true
    link-external-icon: true
    linkcolor: magenta
    urlcolor: magenta
    citecolor: magenta
    cite-method: biblatex
    biblatexoptions: maxbibnames=99, style=numeric, giveninits=true, url=true
    callout-appearance: simple
    callout-icon: true
    include-in-header:
      - text: |
          \usepackage{scrlayer-scrpage}
          \lohead{Numbers, Sequences and Series}
          \cohead{}
          \rohead{Page \pagemark}
          \lofoot{}
          \cofoot{}
          \rofoot{}
          \setheadsepline{0.5pt}
          \addtokomafont{pageheadfoot}{\color{gray}\textnormal}
          \setkomafont{pagenumber}{}
          \usepackage{fvextra}
          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}

  



crossref:
  eq-prefix: ""


filters:
  - custom-numbered-blocks

custom-numbered-blocks:
  groups:
    thmlike:
      colors: [f4cce0, db4d92]
      boxstyle: foldbox.simple
      collapse: false
      listin: [mathstuff]
    todos: default  
  
  classes:
    
    Theorem:
      group: thmlike
    
    Corollary:
      group: thmlike
    
    Conjecture:
      group: thmlike

    Proposition:
      group: thmlike
    
    Question: 
      group: thmlike

    Definition:
      group: thmlike
      colors: [c6e6ed, 1995ad]

    Remark: 
      group: thmlike
      colors: [bce5de, 21aa93]

    Example: 
      group: thmlike
      colors: [bce5de, 21aa93]
      numbered: false

    Proof:
      group: thmlike
      colors: [f1f1f2, c0c0c1]
      numbered: false

    TODO:
      label: "To do"
      colors: [e7b1b4, 8c3236]
      group: todos
      listin: [stilltodo]
      
    DONE:
      label: "Done"
      colors: [cce7b1, 86b754]  
      group: todos
